swagger: "2.0"
info:
  description: Cat Snap
  version: "0.1.0"
  contact:
    email: shreyachandradev@gmail.com
  title: Codecademy
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
  - multipart/form-data
  - application/x-www-form-urlencoded
  - application/octet-stream
  - application/javascript
  - image/jpeg
produces:
  - application/json
  - multipart/form-data

tags:
  - name: Cat-Snaps
    description: Pictures of cats

paths:
  /cat-snap:
    x-swagger-router-controller: snap
    post:
      description: Upload a cat snap
      tags:
        - Cat-Snaps
      operationId: uploadSnaps
      parameters:
        - name: image
          in: body
          description: image to be uploaded.
          required: true
          schema:
            $ref: '#/definitions/FileCheck'
      responses:
        201:
          description: Returns the Snap information.
          schema:
            type: object
        400:
          description: Bad Json Formatting
          schema:
            type: object
  #   get:
  #     description: get all snaps.
  #     tags:
  #       - Cat-Snaps
  #     operationId: listSnaps
  #     responses:
  #       201:
  #         description: Returns the snap information.
  #         schema:
  #           type: object
  #       400:
  #         description: Bad Json Formatting
  #         schema:
  #           type: object
  #   delete:
  #     description: get all snaps.
  #     tags:
  #       - Cat-Snaps
  #     operationId: deleteSnaps
  #     parameters:
  #       - in: body
  #         name: body
  #         description: delete snap.
  #         required: true
  #         schema:
  #           type: object
  #     responses:
  #       201:
  #         description: Returns the snap information.
  #         schema:
  #           type: object
  #       400:
  #         description: Bad Json Formatting
  #         schema:
  #           type: object
  # /cat-snap/{id}:
  #   x-swagger-router-controller: snap
  #   get:
  #     description: Get a cat Snap
  #     tags:
  #       - Cat-Snaps
  #     operationId: getSnapsById
  #     parameters:
  #       - name: imageId
  #         in: path
  #         description: fetch image using imageId.
  #         required: true
  #         schema:
  #           type: string
  #     responses:
  #       201:
  #         description: Returns the Snap information.
  #         schema:
  #           type: object
  #       400:
  #         description: Bad Json Formatting
  #         schema:
  #           type: object

definitions:
  FileCheck:
    type: object
    properties:
      file:
        type: string
        format: binary
#   Error:
#     required:
#       - message
#     properties:
#       message:
#         type: string

#   CatSnapPost:
#     type: object
#     required:
#       - imageUrl
#       - imageId
#       - username
#       - email
#     properties:
#       username:
#         type: string
#         pattern: ^(?=.*[0-9])(?=.*[a-zA-Z])([a-zA-Z0-9]+)$
#       imageId:
#         type: string
#         pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}
#       imageUrl:
#         type: string
#         # pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}
#       email:
#         type: string
#         pattern: (^[\s]{0}$)|(^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$)
